version: "3"
services:
  backend:
    command: npm run dev
    depends_on:
      - database
    env_file: ./config/backend.env
    environment:
      - DATABASE_HOST=database
    image: node:16
    ports:
      - 1337:1337
    volumes:
      - ./backend:/home/node/app
    working_dir: /home/node/app
  database:
    image: postgres
    environment:
      POSTGRES_DB: snippets
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    command: npm run dev
    depends_on:
      - backend
    env_file: ./config/frontend.env
    image: node:16
    ports:
      - 3000:3000
    user: node
    volumes:
      - ./frontend:/home/node/app
    working_dir: /home/node/app
volumes:
  database:
    driver: local
