version: "3"
services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: snippets
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data