version: "3"
services:
  backend:
    build: ./backend/
    depends_on:
      - database
    env_file: ./config/backend.env
    environment:
      DATABASE_HOST: database
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: production
    expose:
      - 1337
    restart: unless-stopped
    volumes:
      - ./backend/snippets:/home/node/app/snippets
      - ./backend/uploads:/home/node/app/uploads
    working_dir: /home/node/app
  database:
    image: postgres
    environment:
      POSTGRES_DB: snippets
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    expose:
      - 5432
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data
  frontend:
    command: bash -c '/test-endpoint.sh backend 1337 && npm run build && npm run start'
    depends_on:
      - backend
    env_file: ./config/frontend.env
    environment:
      - NODE_ENV=production
    expose:
      - 3000
    image: node:16
    restart: unless-stopped
    user: node
    volumes:
      - ./frontend:/home/node/app
      - ./scripts/test-endpoint.sh:/test-endpoint.sh
    working_dir: /home/node/app
  nginx:
    command: bash -c '/test-endpoint.sh backend 1337 && echo "Starting NGiNX..." && nginx -g "daemon off;"'
    depends_on:
      - frontend
    image: nginx
    ports:
      - ${PORT:-9000}:80
    restart: unless-stopped
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./scripts/test-endpoint.sh:/test-endpoint.sh
